logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
spring:
  h2:
    console:
      enabled: true
      path: "/h2-console"
  datasource:
    url: "jdbc:h2:mem:testdb"
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: false
        show_sql: false
